In [ ]:
%load_ext wurlitzer # redirect C/C++ log to ipython

# tensorflow

In [ ]:
import tensorflow as tf

# log-related
from tensorflow.compat.v1.logging import log, log_if, log_first_n, set_verbosity
from tensorflow.compat.v1.logging import INFO, ERROR, DEBUG, WARN

set_verbosity(INFO)


## logging format

In [ ]:
import logging
import logging.handlers

tfLog = logging.getLogger('tensorflow')
# adds .1s after %(levelname) in order to be "I" instead of "INFO"
# changes datetime format as well
formatter = logging.Formatter('[%(levelname).1s %(asctime)s %(filename)s:\
%(lineno)d] %(message)s',datefmt='%m-%d %H:%M')
# add formatter to each handler (default one)
for h in tfLog.handlers:
    h.setFormatter(formatter)
    
set_verbosity(INFO)

In [ ]:
log(INFO,f"version:{tf.__version__} with GPU? {tf.test.is_gpu_available()}")

## common settings

In [ ]:
# 按需设置显存
gpu_options = tf.GPUOptions(allow_growth=True)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))   

禁用gpu

In [ ]:
import os
os.environ["CUDA_VISIBLE_DEVICES"]="-1"

## app.flags usage

In [ ]:
tf.app.flags.DEFINE_string('gpus', None, 'gpus to use')
tf.app.flags.DEFINE_integer('batch_size', 5, 'batch size')

# torch

## difference between expand and repeat

In [12]:
y = torch.tensor([[1], [2], [3]])
x = torch.tensor([1,2,3])

In [63]:
x.repeat(3, 2)
y.repeat(3, 2)
y.expand(3, 2)
print(f"x.size is {x.size} and size after repeat is {x.repeat(3, 2).size()}" )
print(f"y.size is {y.size} and size after repeat is {y.repeat(3, 2).size()}" )
print(f"y.size is {y.size} and size after expand is {y.expand(3, 2).size()}" )

tensor([[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]])

tensor([[1, 1],
        [2, 2],
        [3, 3],
        [1, 1],
        [2, 2],
        [3, 3],
        [1, 1],
        [2, 2],
        [3, 3]])

tensor([[1, 1],
        [2, 2],
        [3, 3]])

x.size is <built-in method size of Tensor object at 0x7f4eb3f96828> and size after repeat is torch.Size([3, 6])
y.size is <built-in method size of Tensor object at 0x7f4eb369e360> and size after repeat is torch.Size([9, 2])
y.size is <built-in method size of Tensor object at 0x7f4eb369e360> and size after expand is torch.Size([3, 2])


# gym

In [71]:
import gym
gym.__version__

'0.15.3'

## CartPole-v0

In [ ]:
env = gym.make('CartPole-v0') 
env.seed(1) # 设置env随机种子
env.observation_space  # 速度，角速度，x
env.action_space
n_states = env.observation_space.shape[0] # 获取总的状态数
n_actions = env.action_space.n # 获取总的动作数

## Callable
callable就是类的<u>实例</u>可以像函数一样调用

In [8]:
class Stu(object):
    test= 0
    def __init__(self, name):
        self.name = name
    def __call__(self, *args, **kwargs):
        self.run()

    def run(self):
        print('{name} is running'.format(name=self.name))
        
    def updateTest(self,num):
        print(f"id of self.test is {id(self.test)}")
        self.test=num
        print(f"self.test's value and id after change is ({self.test},{id(self.test)})")

stu = Stu('小明')
print(callable(stu))    # True
stu()   
print(id(Stu.test))
stu.updateTest(3)

True
小明 is running
93915877628576
id of self.test is 93915877628576
self.test's value and id after change is (3,93915877628672)
